# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0719a934660aefbd753240f977d6f38e5fbc38864da84b7202ee4c064b9da6b4bda88cf038cff872589dfadbad13fafd6b7c47391c292a03b537712f194fb578

test:
  secret_key_base: 164bb6dfa6b2a511781d3beb68aa940b19552e304c54fd07386d4d71dfd69e13a4daae849951ae3db550dcd36c25099b9d48e797a1f70a81f36187506687f8c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
